### ISSUE TITLE
Waffle ▶︎ GitHub Projects ?

### ISSUE THREAD

**Issue by Zearin** [bigeasy/arguable#229]
I’d never seen a “Waffle” button, like the one in the README.  So I clicked it, and saw a kanban-style project organizer.

Nice.  I love that method for organizing stuff.  

GitHub rolled out its own kanban organizer with [Project Boards](https://help.github.com/articles/about-project-boards/).

Perhaps switching to GitHub’s would “remove barriers”/“bring it closer” and make project management a bit easier…?

**Comment by bigeasy** [comment]
Yes. Doing so now.
